 * Serving Flask app "controller/app.py" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 281-121-686
134.190.231.65 - - [10/Mar/2020 19:21:41] "[37mGET /test HTTP/1.1[0m" 200 -
134.190.253.86 - - [10/Mar/2020 19:22:49] "[37mGET /test HTTP/1.1[0m" 200 -
134.190.253.86 - - [10/Mar/2020 19:23:10] "[33mGET /login HTTP/1.1[0m" 404 -
 * Detected change in '/home/ubuntu/csci-4145-project-api-docs/sharebook/controller/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 281-121-686
134.190.253.86 - - [10/Mar/2020 19:39:46] "[37mGET /login HTTP/1.1[0m" 200 -
134.190.253.86 - - [10/Mar/2020 19:40:13] "[31m[1mPOST /ads/1234 HTTP/1.1[0m" 405 -
134.190.253.86 - - [10/Mar/2020 19:40:20] "[37mPUT /ads/1234 HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 19:50:19] "[37mOPTIONS /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 19:50:19] "[37mGET /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 19:52:04] "[33mOPTIONS /createAccount HTTP/1.1[0m" 404 -
134.190.231.65 - - [10/Mar/2020 19:52:42] "[37mOPTIONS /createaccount HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 19:52:42] "[37mPOST /createaccount HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 19:52:42] "[37mOPTIONS /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 19:52:42] "[37mGET /login HTTP/1.1[0m" 200 -
 * Detected change in '/home/ubuntu/csci-4145-project-api-docs/sharebook/controller/app.py', reloading
2020-03-10 20:39:46
2020-03-10 19:40:20.679688
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 281-121-686
134.190.231.65 - - [10/Mar/2020 19:55:06] "[37mOPTIONS /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 19:55:06] "[37mGET /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 20:02:36] "[37mOPTIONS /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 20:02:37] "[37mGET /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 20:03:18] "[37mOPTIONS /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 20:03:18] "[37mGET /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 20:07:09] "[37mOPTIONS /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 20:07:10] "[37mGET /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 20:07:34] "[37mOPTIONS /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 20:07:34] "[37mGET /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 20:07:40] "[37mGET /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 20:08:44] "[37mOPTIONS /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 20:08:44] "[37mGET /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 20:09:05] "[37mOPTIONS /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 20:09:05] "[37mGET /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 20:10:05] "[37mOPTIONS /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 20:10:09] "[37mGET /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 20:10:41] "[37mOPTIONS /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 20:10:41] "[37mGET /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 20:11:32] "[37mOPTIONS /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 20:11:32] "[37mGET /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 20:11:43] "[37mOPTIONS /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 20:11:43] "[37mGET /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 20:15:34] "[37mOPTIONS /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 20:15:34] "[37mGET /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 20:15:49] "[37mOPTIONS /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 20:15:49] "[37mGET /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 20:16:01] "[37mOPTIONS /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 20:16:01] "[37mGET /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 20:20:53] "[37mOPTIONS /login HTTP/1.1[0m" 200 -
134.190.231.65 - - [10/Mar/2020 20:20:53] "[37mGET /login HTTP/1.1[0m" 200 -
209.17.96.234 - - [10/Mar/2020 20:26:41] "[33mGET / HTTP/1.0[0m" 404 -
 * Detected change in '/home/ubuntu/csci-4145-project-api-docs/sharebook/controller/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 281-121-686
 * Serving Flask app "controller/app.py" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 281-121-686
134.190.143.253 - - [11/Mar/2020 13:43:00] "[35m[1mGET /test HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/ubuntu/csci-4145-project-api-docs/sharebook/controller/app.py", line 1, in <module>
    from flask import Flask, request, jsonify, render_template, status
ImportError: cannot import name 'status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/csci-4145-project-api-docs/sharebook/venv/lib/python3.6/site-packages/flask/cli.py", line 338, in __call__
    self._flush_bg_loading_exception()
  File "/home/ubuntu/csci-4145-project-api-docs/sharebook/venv/lib/python3.6/site-packages/flask/cli.py", line 326, in _flush_bg_loading_exception
    reraise(*exc_info)
  File "/home/ubuntu/csci-4145-project-api-docs/sharebook/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/csci-4145-project-api-docs/sharebook/venv/lib/python3.6/site-packages/flask/cli.py", line 314, in _load_app
    self._load_unlocked()
  File "/home/ubuntu/csci-4145-project-api-docs/sharebook/venv/lib/python3.6/site-packages/flask/cli.py", line 330, in _load_unlocked
    self._app = rv = self.loader()
  File "/home/ubuntu/csci-4145-project-api-docs/sharebook/venv/lib/python3.6/site-packages/flask/cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "/home/ubuntu/csci-4145-project-api-docs/sharebook/venv/lib/python3.6/site-packages/flask/cli.py", line 247, in locate_app
    "\n\n{tb}".format(name=module_name, tb=traceback.format_exc())
flask.cli.NoAppException: While importing "sharebook.controller.app", an ImportError was raised:

Traceback (most recent call last):
  File "/home/ubuntu/csci-4145-project-api-docs/sharebook/venv/lib/python3.6/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/home/ubuntu/csci-4145-project-api-docs/sharebook/controller/app.py", line 1, in <module>
    from flask import Flask, request, jsonify, render_template, status
ImportError: cannot import name 'status'
134.190.143.253 - - [11/Mar/2020 13:43:01] "[37mGET /test?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
134.190.143.253 - - [11/Mar/2020 13:43:01] "[37mGET /test?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
134.190.143.253 - - [11/Mar/2020 13:43:01] "[37mGET /test?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
134.190.143.253 - - [11/Mar/2020 13:43:01] "[37mGET /test?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
134.190.143.253 - - [11/Mar/2020 13:43:01] "[37mGET /test?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
